language: go
go:
  - 1.9.x
services:
  - mysql
install:
  - go get github.com/tools/godep
  - go get github.com/mattn/goveralls
script:
  - godep restore
  - make

after_success:
  - make test
  - $HOME/gopath/bin/goveralls -repotoken lvzhxLUsIPqFXYim1uxSdxSnRyG4gh8sr
