apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "redp.fullname" . }}
  labels:
    app: {{ template "redp.name" . }}
    chart: {{ template "redp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "redp.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "redp.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ["go"]
          args: ["test", "-v","./..."]
          env:
          - name: MYSQL_HOST
            value: {{ template "mysql.hostname" . }}
          - name: MYSQL_USERNAME
            value: {{ .Values.mysql.mysqlUser | quote }}
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: {{ template "redp.fullname" . }}
                key: mysql-password
          - name: MYSQL_PORT
            value: "{{ .Values.mysql.service.port }}"
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
