
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "redp.fullname" . }}
  labels:
    app: {{ template "redp.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  mysql-password: {{ .Values.mysql.mysqlPassword | b64enc | quote }}