apiVersion: v1
kind: Service
metadata:
  name: {{ template "redp.fullname" . }}
  labels:
    app: {{ template "redp.name" . }}
    chart: {{ template "redp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}